import type { Lead, Activity, Task, User } from './types';
import { PlaceHolderImages } from './placeholder-images';

export const users: User[] = [
  { id: 'user-1', name: 'Alexandru Popescu', avatar: PlaceHolderImages[0].imageUrl },
  { id: 'user-2', name: 'Elena Ionescu', avatar: PlaceHolderImages[1].imageUrl },
  { id: 'user-3', name: 'Andrei Vasile', avatar: PlaceHolderImages[2].imageUrl },
];

export const leads: Lead[] = [
  {
    id: 'lead-1',
    full_name: 'Ana Maria Preda',
    first_name: 'Ana Maria',
    last_name: 'Preda',
    company_name: 'Preda Imobiliare PFA',
    business_type: 'PFA',
    city: 'București',
    county: 'București',
    phone: '+40 722 123 456',
    email: 'ana.preda@example.com',
    website: 'predaimobiliare.ro',
    source: 'Scraper X',
    source_url: 'http://example.com/source1',
    active_listings_count: 5,
    independent_score: 85,
    classification: 'likely_independent',
    lead_status: 'qualified',
    outreach_status: 'in_sequence',
    owner_id: 'user-1',
    created_at: '2024-05-20T10:00:00Z',
    last_contact_at: '2024-05-22T14:30:00Z',
    owner: users[0],
    hasIndependentPhrase: true,
    isPersonalNameDetected: true,
    hasSoloBusinessIndicators: true,
    isSingleCityActivity: true,
    noLargeBrandDetected: true,
    hasSoloOperatorSignals: true,
    hasLargeAgencyBrand: false,
    hasMultipleOfficeLocations: false,
    hasTeamWording: false,
    hasFranchiseOrCorporateWording: false,
  },
  {
    id: 'lead-2',
    full_name: 'Mihai Stoica',
    first_name: 'Mihai',
    last_name: 'Stoica',
    company_name: 'Stoica Properties',
    business_type: 'SRL',
    city: 'Cluj-Napoca',
    county: 'Cluj',
    phone: '+40 745 987 654',
    email: 'mihai.s@stoicaprop.com',
    website: 'stoicaprop.com',
    source: 'API Import',
    source_url: 'http://example.com/source2',
    active_listings_count: 12,
    independent_score: 65,
    classification: 'possible_independent',
    lead_status: 'contacted',
    outreach_status: 'completed',
    owner_id: 'user-2',
    created_at: '2024-05-19T11:30:00Z',
    last_contact_at: '2024-05-21T09:00:00Z',
    owner: users[1],
    hasIndependentPhrase: false,
    isPersonalNameDetected: true,
    hasSoloBusinessIndicators: false,
    isSingleCityActivity: true,
    noLargeBrandDetected: true,
    hasSoloOperatorSignals: false,
    hasLargeAgencyBrand: false,
    hasMultipleOfficeLocations: false,
    hasTeamWording: false,
    hasFranchiseOrCorporateWording: false,
  },
  {
    id: 'lead-3',
    full_name: 'Global Estate',
    first_name: '',
    last_name: '',
    company_name: 'Global Estate Group',
    business_type: 'SA',
    city: 'Timișoara',
    county: 'Timiș',
    phone: '+40 356 401 234',
    email: 'contact@globalestate.ro',
    website: 'globalestate.ro',
    source: 'Scraper Y',
    source_url: 'http://example.com/source3',
    active_listings_count: 150,
    independent_score: 15,
    classification: 'agency',
    lead_status: 'reviewed',
    outreach_status: 'not_started',
    owner_id: 'user-1',
    created_at: '2024-05-18T15:00:00Z',
    last_contact_at: null,
    owner: users[0],
    hasIndependentPhrase: false,
    isPersonalNameDetected: false,
    hasSoloBusinessIndicators: false,
    isSingleCityActivity: false,
    noLargeBrandDetected: false,
    hasSoloOperatorSignals: false,
    hasLargeAgencyBrand: true,
    hasMultipleOfficeLocations: true,
    hasTeamWording: true,
    hasFranchiseOrCorporateWording: true,
  },
  {
    id: 'lead-4',
    full_name: 'Cristina Dinu',
    first_name: 'Cristina',
    last_name: 'Dinu',
    company_name: 'CD Imobiliare',
    business_type: 'SRL',
    city: 'Iași',
    county: 'Iași',
    phone: '+40 733 555 888',
    email: 'cristina@cdimob.ro',
    website: 'cdimob.ro',
    source: 'Scraper X',
    source_url: 'http://example.com/source4',
    active_listings_count: 8,
    independent_score: 78,
    classification: 'likely_independent',
    lead_status: 'replied',
    outreach_status: 'replied',
    owner_id: 'user-2',
    created_at: '2024-05-21T08:00:00Z',
    last_contact_at: '2024-05-23T11:00:00Z',
    owner: users[1],
    hasIndependentPhrase: false,
    isPersonalNameDetected: true,
    hasSoloBusinessIndicators: false,
    isSingleCityActivity: true,
    noLargeBrandDetected: true,
    hasSoloOperatorSignals: true,
    hasLargeAgencyBrand: false,
    hasMultipleOfficeLocations: false,
    hasTeamWording: false,
    hasFranchiseOrCorporateWording: false,
  },
  {
    id: 'lead-5',
    full_name: 'Florin Popa',
    first_name: 'Florin',
    last_name: 'Popa',
    company_name: 'FP Consulting',
    business_type: 'PFA',
    city: 'Constanța',
    county: 'Constanța',
    phone: '+40 766 123 789',
    email: 'florin.popa@consulting.com',
    website: 'fpconsulting.ro',
    source: 'API Import',
    source_url: 'http://example.com/source5',
    active_listings_count: 3,
    independent_score: 92,
    classification: 'likely_independent',
    lead_status: 'demo_booked',
    outreach_status: 'replied',
    owner_id: 'user-1',
    created_at: '2024-05-22T12:00:00Z',
    last_contact_at: '2024-05-24T10:00:00Z',
    owner: users[0],
    hasIndependentPhrase: true,
    isPersonalNameDetected: true,
    hasSoloBusinessIndicators: true,
    isSingleCityActivity: true,
    noLargeBrandDetected: true,
    hasSoloOperatorSignals: true,
    hasLargeAgencyBrand: false,
    hasMultipleOfficeLocations: false,
    hasTeamWording: false,
    hasFranchiseOrCorporateWording: false,
  },
];

export const recentActivities: Activity[] = [
  {
    id: 'act-1',
    lead_name: 'Cristina Dinu',
    event_type: 'email_sent',
    channel: 'email',
    description: 'Sent follow-up email from "Independent Agent" campaign.',
    timestamp: '2024-05-23T11:00:00Z',
    user: users[1],
  },
  {
    id: 'act-2',
    lead_name: 'Florin Popa',
    event_type: 'note_added',
    channel: 'system',
    description: 'Added note: "Interested in the Pro plan. Mentioned having a partner."',
    timestamp: '2024-05-24T10:05:00Z',
    user: users[0],
  },
  {
    id: 'act-3',
    lead_name: 'Global Estate',
    event_type: 'status_changed',
    channel: 'system',
    description: 'Status changed from New to Reviewed. Classified as Agency.',
    timestamp: '2024-05-18T16:00:00Z',
    user: users[0],
  },
  {
    id: 'act-4',
    lead_name: 'Ana Maria Preda',
    event_type: 'task_created',
    channel: 'task',
    description: 'Created task: "Call to confirm demo time."',
    timestamp: '2024-05-22T14:35:00Z',
    user: users[0],
  },
];

export const tasks: Task[] = [
  {
    id: 'task-1',
    lead_name: 'Ana Maria Preda',
    type: 'call',
    due_date: '2024-05-25T14:00:00Z',
    is_overdue: false,
  },
  {
    id: 'task-2',
    lead_name: 'Mihai Stoica',
    type: 'follow_up',
    due_date: '2024-05-24T09:00:00Z',
    is_overdue: true,
  },
  {
    id: 'task-3',
    lead_name: 'Cristina Dinu',
    type: 'demo',
    due_date: '2024-05-28T10:00:00Z',
    is_overdue: false,
  },
];
